[environments.testing]
url = "jdbc:postgresql://localhost:5433/postgres"
user = "postgres"
password = "docker"
schemas = ["schema1"]
defaultSchema = "schema1"
cleanDisabled = true

[environments.prod]
url = "jdbc:postgresql://localhost:5432/postgres"
user = "postgres"
password = "docker"
schemas = ["schema1"]
defaultSchema = "schema1"
cleanDisabled = true

[flyway]
environment = "testing"
